### ISSUE TITLE
misc typos etc

### ISSUE THREAD

**Issue by eldobbins** [iamchrisser/nga-dataset-best-practices#1]
This looks so nice!  I'm excited.

I noticed these differences with the Google Doc. 

1. Table at the end on error codes isn't properly formatted in the website version.  Looks OK in the repo, though, so I don't know what it's missing.
2. Tidy data section: "In short ..." should be part of the next paragraph, not part of item 3
3. cruise codes: Looks like the T|S bit got turned into a table instead of staying "or"
4. Data File Formatting: 
  a. columns names parentheses are mismatched around "specification"
  b. I think "Data type" and the first sentence under should be part of the section above on filenames.  The next 2 lines continue on with variable names.
5. standard columns: first 6 are missing their descriptions.  Was that on purpose?
6. standard columns: I think the " in the index might be better as ...
7. missing value flags: can we list -999 as acceptable?  Or are those being changed in data files?
8. Dates: In the google doc, I made a comment about using 'Z' in dates and how it doesn't work in ODV.  I don't know if anyone else has run into this. I got around this by calling the column "Date_[UTC]" then leaving out the Z. But this document says without a Z, it's local time. Is that OK?  if so, could you add "unless otherwise noted in the column name"?

**Comment by iamchrisser** [comment]
Resolved 2-7. I'm still working on the flag values table, and the dates needs to be a larger conversation.

**Comment by iamchrisser** [comment]
ok, I also fixed the table. I'm going to close this and open a new issue just for the date stuff.
